### ISSUE TITLE
Support for soft RAM limit?

### ISSUE THREAD

**Issue by pete-woods** [uber-go/automaxprocs#56]
Hello 👋🏻 

Are there any plans to support the soft RAM limit introduced in Go 1.19?

(Either in this library or a new one)

**Comment by rabbbit** [comment]
Hey,

Just acknowledging here that we saw the question. We're discussing this, but we don't have an exact plan yet.

**Comment by StevenACoffman** [comment]
This is appears to be a quick attempt at doing that: https://github.com/KimMachineGun/automemlimit
it used `containerd` under the hood, but I've not tried using it under various container runtimes, non-Linux OSes like darwin, etc.

**Comment by StevenACoffman** [comment]
[GOMAXPROCS](https://tip.golang.org/pkg/runtime/#GOMAXPROCS) and [GOMEMLIMIT](https://weaviate.io/blog/2022/08/GOMEMLIMIT-a-Game-Changer-for-High-Memory-Applications.html) are environmental values that can help the application's Go Runtime to perform better.

We could easily (and naively) set `GOMEMLIMIT` to be **equal** to the container limit like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: go-k8s-memory
spec:
  containers:
  - name: go-k8s-memory
    image: ko://go-k8s-memory
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 64Mi        // <--- limit on container memory
        cpu: "1"
      requests:
        memory: 62Mi
        cpu: "0.2"
    env:
    - name: GOMEMLIMIT
      valueFrom:            // <--- value taken from downwards API
        resourceFieldRef:
          resource: limits.memory

```

However, the Go documentation has this note:

> In this case, a good rule of thumb is to leave an additional 5-10% of headroom to account for memory sources the Go runtime is unaware of.

Examples of these sources might include:

+ OS kernel memory held on behalf of the process
+ memory allocated by C code
+ memory mapped by syscall.Mmap

As a result, it would be best if we could correctly introspect the container's memory limit and set `GOMEMLIMIT` to 90-90% of the container's memory limit.
